services:
  - type: web
    name: 100-algo-match
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node --loader tsx/esm server.ts
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyBnQbrXYbrwB2GvkDCSCBd284DT_EnPMAQ
      - key: FOOTBALL_DATA_KEY
        value: b59ca296256c46b3bdda386be1844efd
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
