services:
  - type: web
    name: 100-algo-match
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node --loader tsx/esm server.ts
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: FOOTBALL_DATA_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
